### ISSUE TITLE
Context & target images

### ISSUE THREAD

**Issue by Golbstein** [cvg/depthsplat#11]
Hi
I don’t think I saw you mention it in your paper, but what exactly is the purpose of context and target images in the dataloader?
From what I could see, there’s always 2 context images and 4 target images which are all different.

My guess is that based on the paired context images you’re trying to predict the 4 target images. Am I right? If so, why do you choose 4 target images and not 1, or 2 or any other number?

🙏 thanks

**Comment by haofeixu** [comment]
Hi, the context images are the inputs to the network, and the model predicts target views in novel poses.

Yes, you are right. On re10k, we take 2 images as input and predict 4 target images. We choose 4 by following previous methods like pixelSplat and MVSplat. However, you can flexbily adjust it according to your needs (more target views potentially leads to slightly improved results. However, it also introduces higher cost in training).

**Comment by Golbstein** [comment]
Is it possible to take more than 2 images? Or is it even necessary?

**Comment by haofeixu** [comment]
Hi, please kindly check the dataloader here: https://github.com/cvg/depthsplat/blob/main/src/dataset/dataset_dl3dv.py, which can support arbitrary number of input images. Please refer to this script for an example of how to use it: https://github.com/cvg/depthsplat/blob/main/scripts/dl3dv_256x448_depthsplat_base.sh

**Comment by Golbstein** [comment]
what are these parameters?
model.encoder.num_scales=2 \
model.encoder.upsample_factor=4 \
model.encoder.lowest_feature_resolution=8 \

I see that they are different when training on re vs dl dataset

**Comment by haofeixu** [comment]
Hi, these are the configs of our multi-view branch, where the details can be found in the "Implementation Details" of "Section 4 EXPERIMENTS" in our paper.
