### ISSUE TITLE
DL3DV processing scripts

### ISSUE THREAD

**Issue by liorfritz** [cvg/depthsplat#13]
Really awesome work, and big thank you for sharing your code!
If I understand correctly, you follow pixelsplat's scripts to process RE10K. Can you kindly share the scripts to convert DL3DV?

**Comment by haofeixu** [comment]
Hi, thank you for your kind words. The processing scripts are available now and kindly check the details here: https://github.com/cvg/depthsplat/blob/main/DATASETS.md
