### ISSUE TITLE
How to save the gaussians

### ISSUE THREAD

**Issue by CanCanZeng** [cvg/depthsplat#14]
As discussed in another issue https://github.com/cvg/depthsplat/issues/6, I want to save the gaussians generated by the algorithm, but by the definition of **Gaussian** class, I found that the algorithm directly predicts the **covariance**, not the **scales** and **rotations**. How can I recover the scales and rotations from the covariance?
Another question is what is the reason why the author chose to directly predict the covariance instead of the scales and rotations?

**Comment by haofeixu** [comment]
Please note that we predict scales and rotations, instead of directly predicting the covariance (https://github.com/cvg/depthsplat/blob/main/src/model/encoder/common/gaussian_adapter.py#L65-L68).

**Comment by CanCanZeng** [comment]
I'm sorry for my carelessness.
I finally saved the Gaussians, but the result is a bit strange when displayed in https://playcanvas.com/supersplat/editor. I suspect there may be two issues, one is the influence of extrinsic data, and I am not very familiar with the coordinate system definitions of each data here. For example, are **means** of Gaussians obtained from the encoder defined in a global or local coordinate system? Are **rotations** and scales defined in a global or local coordinate system? The harmonics coefficient should also be related to the coordinate system. Another point is that it seems that the `sh_degree` of the **harmonics** output from the encoder is 4. Can it be changed to 3 without retraining?
![image](https://github.com/user-attachments/assets/0eb8539b-6789-45d9-875a-79ca4257b69b)

**Comment by haofeixu** [comment]
Hi, some post-processing steps are performed when saving the Gaussians, which can be found here: https://github.com/cvg/depthsplat/blob/main/src/model/ply_export.py#L26

It could be possible to change the `sh_degree` from 4 to 3 without retraining. For example, you can remove the parameters for the high degrees.
