### ISSUE TITLE
Will scripts for scannet released soon ?

### ISSUE THREAD

**Issue by Made-Gpt** [cvg/depthsplat#15]
Great Work!
I note that experiment on scannet is mentioned in the paper, will you release scripts for scannet in the future ?

**Comment by haofeixu** [comment]
Hi, we conducted depth experiments on scannet based on the codebase of [UniMatch](https://github.com/autonomousvision/unimatch), and the view synthsis experiments were not performed on scannet.

**Comment by Made-Gpt** [comment]
> Hi, we conducted depth experiments on scannet based on the codebase of [UniMatch](https://github.com/autonomousvision/unimatch), and the view synthsis experiments were not performed on scannet.

I see, thanks !
But I am still wondering if depthsplat is able to synthetize new view and reconstruct the whole scene on scannet.

**Comment by haofeixu** [comment]
This is an interesting question, feel free to train/evaluate our model on scannet (kindly check https://github.com/cvg/depthsplat/blob/main/DATASETS.md for data preparation). Thanks.

**Comment by Made-Gpt** [comment]
> This is an interesting question, feel free to train/evaluate our model on scannet (kindly check https://github.com/cvg/depthsplat/blob/main/DATASETS.md for data preparation). Thanks.

OK, I will try it !
