### ISSUE TITLE
Visualizer

### ISSUE THREAD

**Issue by MichaelYu781** [cvg/depthsplat#18]
Hi, is there an official viewer for gaussians available? I develop a viewer in nerfstudio, but the usage is somewhat inconvenient.
![image](https://github.com/user-attachments/assets/c5375a7a-0992-4a8a-9166-0743b84ce290)

**Comment by haofeixu** [comment]
Hi, we also used external viewers after saving Gaussian parameters. Besides nerfstudio's viewer, this one could also be an option: https://antimatter15.com/splat/
