### ISSUE TITLE
training multi-view context images input? The question about view_sampler

### ISSUE THREAD

**Issue by VillardX** [cvg/depthsplat#19]
Hi, thanks for your great work!

Your project code use *view_sampler_bounded.py* by default, which only has 2 context views as input.

My own customed dataset has more than 2 context views. And I try to use *view_sampler_arbitrary.py* and modify the *arbitrary.yaml* as follows,
![image](https://github.com/user-attachments/assets/5afd399e-86dd-4013-9f71-ec0d7f674d64)

However, when I run the training code, I get the error as follows,
![image](https://github.com/user-attachments/assets/d462278c-29b0-4685-92e1-e5d30eefc697)

which seems that the grid_sampler get an error.

Could you please provide some advice about it please?

Best regards,
VillardX

**Comment by haofeixu** [comment]
Hi, for more than two input views, please check this dataloader https://github.com/cvg/depthsplat/blob/main/src/dataset/dataset_dl3dv.py and this script for how to use it: https://github.com/cvg/depthsplat/blob/main/scripts/dl3dv_256x448_depthsplat_base.sh#L32-L41

**Comment by haofeixu** [comment]
For the grid_sampler error, you might want to try to use an additional argument in your script:
`model.encoder.grid_sample_disable_cudnn=true`
