### ISSUE TITLE
How to test on custom image inputs

### ISSUE THREAD

**Issue by hbai98** [cvg/depthsplat#22]
Thanks for your great work. I see the inference script to test on the dl3dv dataset, and I wonder how to test on few image inputs to test its performance, especially the rendered video.

**Comment by Golbstein** [comment]
you can simply change the batch to have your data

batch['context']['image'] = your input
batch['context']['extrinsics'] = your extrinsics
batch['context']['intrinsics'] = your intrinsics

batch['target']['extrinsics'] = your desired novel views
