### ISSUE TITLE
Using Depth Information from LiDAR or DepthPro Instead of DepthAnything

### ISSUE THREAD

**Issue by AbedSoleymani** [cvg/depthsplat#3]
Is it possible to use depth information from other sources like LiDAR or more accurate models such as Apple’s DepthPro, instead of DepthAnything, in your model?

**Comment by LiHaodong0217** [comment]
i guass it is make sense.
In fact,if you can get the depth,you can get infer the location of 3DGS(most important attribute of 3DGS)
By the way,Maske support that a purely visual scheme will win the future,haha

**Comment by haofeixu** [comment]
Hi, it's also possible to integrate Depth Pro's monocular features into our model, though end-to-end fine-tuning is necessary to achieve 3D consistent results with Gaussian splatting. For LiDAR, it might be less straightforward to use it in our model.
