### ISSUE TITLE
Can you provide a detailed guide on how to process other images with poses?

### ISSUE THREAD

**Issue by SensenGao** [cvg/depthsplat#32]
I have been reviewing your code for 2-3 days, but I find the data format quite confusing. Could you provide a detailed guide on how to use DepthSplat if I have a certain number of images with poses? I believe the existing instructions in the repository are unclear and difficult to follow, making it challenging to use effectively.

**Comment by synaldoh** [comment]
I have difficulty following it as well, did you manage to do it?
