### ISSUE TITLE
Dataset Processing Details for TartanAir and VKITTI2

### ISSUE THREAD

**Issue by Yang-xiao-uts** [cvg/depthsplat#38]
In your paper, you mentioned:

"For the ablation experiments on the depth task, we mainly use synthetic datasets (TartanAir [55] and VKITTI2 [5]) for training since they provide high-quality ground truth depths."

Could you share how you processed these two datasets, TartanAir and VKITTI2? For instance, how did you handle the resizing of depth maps?

Thank you!

**Comment by haofeixu** [comment]
Hi, we didn't perform resizing for the gt depth, instead we do random cropping with the code here: https://github.com/autonomousvision/unimatch/blob/master/dataloader/depth/augmentation.py#L66

The dataloader follows [unimatch](https://github.com/autonomousvision/unimatch), and here is an example on scannet dataset: https://github.com/autonomousvision/unimatch/blob/master/dataloader/depth/datasets.py#L11
