### ISSUE TITLE
Does this require camera parameters?

### ISSUE THREAD

**Issue by rkakash59** [cvg/depthsplat#4]
Does this method require camera intrinsic and extrinsic parameters. For sparse view reconstruction getting camera parameters is challenging.

**Comment by rkakash59** [comment]
In conclusion:
Our current model requires camera pose information as input along with the multi-view images, removing this requirement would be exciting future work.

**Comment by LiHaodong0217** [comment]
some suggestions for you
1. DUSt3R is better than COLMAP from sparse view camera estimation
2. you can get care about some work on pose-free(InstantSplat,GGRt)
in the future,i believe i can reconstruct 3d scene without pose.
By the way,i recommend you can pay close attention to the author of InstantSplat(zhiweng fan from A&T uni)
